name: 'Firebolt security scan'
description: 'Detect security issues and bad practices in repository'
inputs:
  github-key:
    description: 'Github token'
    required: true
  fossa-key:
    description: 'Deprecated. Kept for backwards-compatibility'
    required: false
  sonar-key:
    description: 'Sonar Cloud API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-key }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar-key }}
