name: 'Firebolt security scan'
description: 'Detect security issues and bad practices in repository'
inputs:
  github-key:
    description: 'Github token'
    required: true
  fossa-key:
    description: 'Deprecated. Kept for backwards-compatibility'
    required: false
  sonar-key:
    description: 'Sonar Cloud API key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify secrets are provided
      shell: bash
      run: |
        if [ -z "${{ inputs.github-key }}" ] && [ -z "${{ inputs.fossa-key }}" ]; then
          echo "No secrets provided. Skipping Sonar check..."
        fi

    - name: SonarCloud Scan
      if: ${{ inputs.sonar-key }} # skip if run from a fork (secrets are empty)
      uses: SonarSource/sonarcloud-github-action@v2.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-key }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ inputs.sonar-key }}
